### ISSUE TITLE
No "pc_pipeline_msgs.msg"

### ISSUE THREAD

**Issue by txchitchat** [CURG/pc_pipeline_launch#1]
when I type the following command in python, it shows:
![image](https://user-images.githubusercontent.com/18459307/38231069-82818e9a-3743-11e8-96cc-7ae6ca2e1d34.png)
There is a line of code in "pc_scene_completion_client/pc_scene_completion_client.py":
import pc_pipeline_msgs.msg
But where is the .msg file? How to generate it?

**Comment by DavidWatkins** [comment]
This is a very old issue that is likely no longer relevant, but to solve this issue you need to build this package: https://github.com/CRLab/pc_pipeline_msgs.
