### ISSUE TITLE
Problem in launching pc_pipeline_launch

### ISSUE THREAD

**Issue by 13285073101** [CURG/pc_pipeline_launch#3]
Hello @jvarley @DavidWatkins
I run this launch.
`
<launch>

    <include file="$(find freenect_launch)/launch/freenect.launch">
        <arg name="depth_registration" value="true" />
        <arg name="bond" value="true" />
        <arg name="data_skip" value="5"/>
    </include>

    <include file="$(find pc_pipeline_launch)/launch/pc_pipeline.launch">
             <arg name="pc_filter/xpassthrough/filter_limit_min" value="0" />
             <arg name="pc_filter/ypassthrough/filter_limit_min" value="0" />
             <arg name="pc_filter/zpassthrough/filter_limit_min" value="0.01" />
             <arg name="pc_filter/xpassthrough/filter_limit_max" value="0.20" />
             <arg name="pc_filter/ypassthrough/filter_limit_max" value="0.30" />
             <arg name="pc_filter/zpassthrough/filter_limit_max" value="1" />
             <arg name="pc_filter/observed_frame_id" value="/camera_rgb_optical_frame" />
             <arg name="pc_filter/filtered_frame_id" value="/ar_marker_14_filtered" />
             <arg name="pc_filter/input_pc_topic" value="/camera/depth_registered/points" />
             <arg name="pc_filter/output_pc_topic" value="/filtered_pc" />
             <arg name="run_partial_mesh" value="False" />
    </include>

    <include file="$(find ar_tracking)/launch/publish_transform.launch"/>
    <include file="$(find ar_tracking)/launch/staubli_barrett_kinect360.launch"/>
    <node pkg="filter_tf" type="filter_tf.py" name="filter_tf_marker8" args="/ar_marker_8/         camera_rgb_optical_frame"/>
    <node pkg="filter_tf" type="filter_tf.py" name="filter_tf_marker14" args="/ar_marker_14 /camera_rgb_optical_frame"/>

</launch>
`
I got these errors.
RLException: roslaunch file contains multiple nodes named [/camera/camera_nodelet_manager].
Please check all <node> 'name' attributes to make sure they are unique.
Also check that $(anon id) use different ids.
The traceback for the exception was written to the log file

What is your advice?
Thanks and waiting for your reply.
Regards,

**Comment by DavidWatkins** [comment]
What's likely happening is another launch file you are calling is trying to load a "camera_nodelet_manager" Check the "staubli_barrett_kinect360.launch" or "freenect.launch" as they are likely both trying to start a camera listener. I am not sure if you need both unless you are using a kinect camera to test this.
